version: '3'

services: 
    rabbitmq:
        image: 'rabbitmq'
        ports: 
            - 5672:5672

    rabbitmq-management:
        image: 'rabbitmq:management'
        ports: 
            - 15672:15672

    worker:
        build: worker
        volumes:
            - ./worker:/app
        environment:
            - PYTHONUNBUFFERED=1
    
    server:
        build: server
        volumes:
            - ./server:/app
        ports:
            - 5000:5000